// Copyright Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
// Modified by Higress Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: extensions/v1alpha1/wasmplugin.proto

// $schema: higress.extensions.v1alpha1.WasmPlugin
// $title: WasmPlugin
// $description: Extend the functionality provided by the envoy through WebAssembly filters.

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Route type for matching rules.
// Extended by Higress
type RouteType int32

const (
	// HTTP route (default)
	RouteType_HTTP RouteType = 0
	// GRPC route
	RouteType_GRPC RouteType = 1
)

// Enum value maps for RouteType.
var (
	RouteType_name = map[int32]string{
		0: "HTTP",
		1: "GRPC",
	}
	RouteType_value = map[string]int32{
		"HTTP": 0,
		"GRPC": 1,
	}
)

func (x RouteType) Enum() *RouteType {
	p := new(RouteType)
	*p = x
	return p
}

func (x RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_v1alpha1_wasmplugin_proto_enumTypes[0].Descriptor()
}

func (RouteType) Type() protoreflect.EnumType {
	return &file_extensions_v1alpha1_wasmplugin_proto_enumTypes[0]
}

func (x RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteType.Descriptor instead.
func (RouteType) EnumDescriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{0}
}

// The phase in the filter chain where the plugin will be injected.
type PluginPhase int32

const (
	// Control plane decides where to insert the plugin. This will generally
	// be at the end of the filter chain, right before the Router.
	// Do not specify `PluginPhase` if the plugin is independent of others.
	PluginPhase_UNSPECIFIED_PHASE PluginPhase = 0
	// Insert plugin before Istio authentication filters.
	PluginPhase_AUTHN PluginPhase = 1
	// Insert plugin before Istio authorization filters and after Istio authentication filters.
	PluginPhase_AUTHZ PluginPhase = 2
	// Insert plugin before Istio stats filters and after Istio authorization filters.
	PluginPhase_STATS PluginPhase = 3
)

// Enum value maps for PluginPhase.
var (
	PluginPhase_name = map[int32]string{
		0: "UNSPECIFIED_PHASE",
		1: "AUTHN",
		2: "AUTHZ",
		3: "STATS",
	}
	PluginPhase_value = map[string]int32{
		"UNSPECIFIED_PHASE": 0,
		"AUTHN":             1,
		"AUTHZ":             2,
		"STATS":             3,
	}
)

func (x PluginPhase) Enum() *PluginPhase {
	p := new(PluginPhase)
	*p = x
	return p
}

func (x PluginPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_v1alpha1_wasmplugin_proto_enumTypes[1].Descriptor()
}

func (PluginPhase) Type() protoreflect.EnumType {
	return &file_extensions_v1alpha1_wasmplugin_proto_enumTypes[1]
}

func (x PluginPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginPhase.Descriptor instead.
func (PluginPhase) EnumDescriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{1}
}

// The pull behaviour to be applied when fetching an OCI image,
// mirroring K8s behaviour.
//
// <!--
// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
// -->
type PullPolicy int32

const (
	// Defaults to IfNotPresent, except for OCI images with tag `latest`, for which
	// the default will be Always.
	PullPolicy_UNSPECIFIED_POLICY PullPolicy = 0
	// If an existing version of the image has been pulled before, that
	// will be used. If no version of the image is present locally, we
	// will pull the latest version.
	PullPolicy_IfNotPresent PullPolicy = 1
	// We will always pull the latest version of an image when applying
	// this plugin.
	PullPolicy_Always PullPolicy = 2
)

// Enum value maps for PullPolicy.
var (
	PullPolicy_name = map[int32]string{
		0: "UNSPECIFIED_POLICY",
		1: "IfNotPresent",
		2: "Always",
	}
	PullPolicy_value = map[string]int32{
		"UNSPECIFIED_POLICY": 0,
		"IfNotPresent":       1,
		"Always":             2,
	}
)

func (x PullPolicy) Enum() *PullPolicy {
	p := new(PullPolicy)
	*p = x
	return p
}

func (x PullPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_v1alpha1_wasmplugin_proto_enumTypes[2].Descriptor()
}

func (PullPolicy) Type() protoreflect.EnumType {
	return &file_extensions_v1alpha1_wasmplugin_proto_enumTypes[2]
}

func (x PullPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPolicy.Descriptor instead.
func (PullPolicy) EnumDescriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{2}
}

type EnvValueSource int32

const (
	// Explicitly given key-value pairs to be injected to this VM
	EnvValueSource_INLINE EnvValueSource = 0
	// *Istio-proxy's* environment variables exposed to this VM.
	EnvValueSource_HOST EnvValueSource = 1
)

// Enum value maps for EnvValueSource.
var (
	EnvValueSource_name = map[int32]string{
		0: "INLINE",
		1: "HOST",
	}
	EnvValueSource_value = map[string]int32{
		"INLINE": 0,
		"HOST":   1,
	}
)

func (x EnvValueSource) Enum() *EnvValueSource {
	p := new(EnvValueSource)
	*p = x
	return p
}

func (x EnvValueSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvValueSource) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_v1alpha1_wasmplugin_proto_enumTypes[3].Descriptor()
}

func (EnvValueSource) Type() protoreflect.EnumType {
	return &file_extensions_v1alpha1_wasmplugin_proto_enumTypes[3]
}

func (x EnvValueSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvValueSource.Descriptor instead.
func (EnvValueSource) EnumDescriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{3}
}

type FailStrategy int32

const (
	// A fatal error in the binary fetching or during the plugin execution causes
	// all subsequent requests to fail with 5xx.
	FailStrategy_FAIL_CLOSE FailStrategy = 0
	// Enables the fail open behavior for the Wasm plugin fatal errors to bypass
	// the plugin execution. A fatal error can be a failure to fetch the remote
	// binary, an exception, or abort() on the VM. This flag is not recommended
	// for the authentication or the authorization plugins.
	FailStrategy_FAIL_OPEN FailStrategy = 1
)

// Enum value maps for FailStrategy.
var (
	FailStrategy_name = map[int32]string{
		0: "FAIL_CLOSE",
		1: "FAIL_OPEN",
	}
	FailStrategy_value = map[string]int32{
		"FAIL_CLOSE": 0,
		"FAIL_OPEN":  1,
	}
)

func (x FailStrategy) Enum() *FailStrategy {
	p := new(FailStrategy)
	*p = x
	return p
}

func (x FailStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_v1alpha1_wasmplugin_proto_enumTypes[4].Descriptor()
}

func (FailStrategy) Type() protoreflect.EnumType {
	return &file_extensions_v1alpha1_wasmplugin_proto_enumTypes[4]
}

func (x FailStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailStrategy.Descriptor instead.
func (FailStrategy) EnumDescriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{4}
}

// <!-- crd generation tags
// +cue-gen:WasmPlugin:groupName:extensions.higress.io
// +cue-gen:WasmPlugin:version:v1alpha1
// +cue-gen:WasmPlugin:storageVersion
// +cue-gen:WasmPlugin:annotations:helm.sh/resource-policy=keep
// +cue-gen:WasmPlugin:subresource:status
// +cue-gen:WasmPlugin:scope:Namespaced
// +cue-gen:WasmPlugin:resource:categories=higress-io,extensions-higress-io
// +cue-gen:WasmPlugin:preserveUnknownFields:pluginConfig,defaultConfig,matchRules.[].config
// +cue-gen:WasmPlugin:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=extensions.higress.io/v1alpha1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type WasmPlugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL of a Wasm module or OCI container. If no scheme is present,
	// defaults to `oci://`, referencing an OCI image. Other valid schemes
	// are `file://` for referencing .wasm module files present locally
	// within the proxy container, and `http[s]://` for .wasm module files
	// hosted remotely.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// SHA256 checksum that will be used to verify Wasm module or OCI container.
	// If the `url` field already references a SHA256 (using the `@sha256:`
	// notation), it must match the value of this field. If an OCI image is
	// referenced by tag and this field is set, its checksum will be verified
	// against the contents of this field after pulling.
	Sha256 string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// The pull behaviour to be applied when fetching an OCI image. Only
	// relevant when images are referenced by tag instead of SHA. Defaults
	// to IfNotPresent, except when an OCI image is referenced in the `url`
	// and the `latest` tag is used, in which case `Always` is the default,
	// mirroring K8s behaviour.
	// Setting is ignored if `url` field is referencing a Wasm module directly
	// using `file://` or `http[s]://`
	ImagePullPolicy PullPolicy `protobuf:"varint,4,opt,name=image_pull_policy,json=imagePullPolicy,proto3,enum=higress.extensions.v1alpha1.PullPolicy" json:"image_pull_policy,omitempty"`
	// Credentials to use for OCI image pulling.
	// Name of a K8s Secret in the same namespace as the `WasmPlugin` that
	// contains a docker pull secret which is to be used to authenticate
	// against the registry when pulling the image.
	ImagePullSecret string `protobuf:"bytes,5,opt,name=image_pull_secret,json=imagePullSecret,proto3" json:"image_pull_secret,omitempty"`
	// Public key that will be used to verify signatures of signed OCI images
	// or Wasm modules. Must be supplied in PEM format.
	VerificationKey string `protobuf:"bytes,6,opt,name=verification_key,json=verificationKey,proto3" json:"verification_key,omitempty"`
	// The configuration that will be passed on to the plugin.
	PluginConfig *structpb.Struct `protobuf:"bytes,7,opt,name=plugin_config,json=pluginConfig,proto3" json:"plugin_config,omitempty"`
	// The plugin name to be used in the Envoy configuration (used to be called
	// `rootID`). Some .wasm modules might require this value to select the Wasm
	// plugin to execute.
	PluginName string `protobuf:"bytes,8,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Determines where in the filter chain this `WasmPlugin` is to be injected.
	Phase PluginPhase `protobuf:"varint,9,opt,name=phase,proto3,enum=higress.extensions.v1alpha1.PluginPhase" json:"phase,omitempty"`
	// Determines ordering of `WasmPlugins` in the same `phase`.
	// When multiple `WasmPlugins` are applied to the same workload in the
	// same `phase`, they will be applied by priority, in descending order.
	// If `priority` is not set, or two `WasmPlugins` exist with the same
	// value, the ordering will be deterministically derived from name and
	// namespace of the `WasmPlugins`. Defaults to `0`.
	Priority *wrapperspb.Int32Value `protobuf:"bytes,10,opt,name=priority,proto3" json:"priority,omitempty"`
	// Specifies the failure behavior for the plugin due to fatal errors.
	FailStrategy FailStrategy `protobuf:"varint,13,opt,name=fail_strategy,json=failStrategy,proto3,enum=higress.extensions.v1alpha1.FailStrategy" json:"fail_strategy,omitempty"`
	// Configuration for a Wasm VM.
	// more details can be found [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#extensions-wasm-v3-vmconfig).
	VmConfig *VmConfig `protobuf:"bytes,11,opt,name=vm_config,json=vmConfig,proto3" json:"vm_config,omitempty"`
	// Extended by Higress, the default configuration takes effect globally
	DefaultConfig *structpb.Struct `protobuf:"bytes,101,opt,name=default_config,json=defaultConfig,proto3" json:"default_config,omitempty"`
	// Extended by Higress, matching rules take effect
	MatchRules []*MatchRule `protobuf:"bytes,102,rep,name=match_rules,json=matchRules,proto3" json:"match_rules,omitempty"`
	// disable the default config
	DefaultConfigDisable *wrapperspb.BoolValue `protobuf:"bytes,103,opt,name=default_config_disable,json=defaultConfigDisable,proto3" json:"default_config_disable,omitempty"`
	// Extended by Higress, references to ConfigMaps for sharded plugin config
	// The controller will watch these ConfigMaps and merge their data into the final config
	ResourceRefs []string `protobuf:"bytes,104,rep,name=resource_refs,json=resourceRefs,proto3" json:"resourceRefs,omitempty"`
	// Extended by Higress, template schema for rendering sharded config
	// Defines the mapping between ConfigMap data keys and placeholder names
	ResourceTemplateSchema []*ResourceTemplateSchemaEntry `protobuf:"bytes,105,rep,name=resource_template_schema,json=resourceTemplateSchema,proto3" json:"resourceTemplateSchema,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WasmPlugin) Reset() {
	*x = WasmPlugin{}
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmPlugin) ProtoMessage() {}

func (x *WasmPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmPlugin.ProtoReflect.Descriptor instead.
func (*WasmPlugin) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{0}
}

func (x *WasmPlugin) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WasmPlugin) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *WasmPlugin) GetImagePullPolicy() PullPolicy {
	if x != nil {
		return x.ImagePullPolicy
	}
	return PullPolicy_UNSPECIFIED_POLICY
}

func (x *WasmPlugin) GetImagePullSecret() string {
	if x != nil {
		return x.ImagePullSecret
	}
	return ""
}

func (x *WasmPlugin) GetVerificationKey() string {
	if x != nil {
		return x.VerificationKey
	}
	return ""
}

func (x *WasmPlugin) GetPluginConfig() *structpb.Struct {
	if x != nil {
		return x.PluginConfig
	}
	return nil
}

func (x *WasmPlugin) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *WasmPlugin) GetPhase() PluginPhase {
	if x != nil {
		return x.Phase
	}
	return PluginPhase_UNSPECIFIED_PHASE
}

func (x *WasmPlugin) GetPriority() *wrapperspb.Int32Value {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *WasmPlugin) GetFailStrategy() FailStrategy {
	if x != nil {
		return x.FailStrategy
	}
	return FailStrategy_FAIL_CLOSE
}

func (x *WasmPlugin) GetVmConfig() *VmConfig {
	if x != nil {
		return x.VmConfig
	}
	return nil
}

func (x *WasmPlugin) GetDefaultConfig() *structpb.Struct {
	if x != nil {
		return x.DefaultConfig
	}
	return nil
}

func (x *WasmPlugin) GetMatchRules() []*MatchRule {
	if x != nil {
		return x.MatchRules
	}
	return nil
}

func (x *WasmPlugin) GetDefaultConfigDisable() *wrapperspb.BoolValue {
	if x != nil {
		return x.DefaultConfigDisable
	}
	return nil
}

func (x *WasmPlugin) GetResourceRefs() []string {
	if x != nil {
		return x.ResourceRefs
	}
	return nil
}

func (x *WasmPlugin) GetResourceTemplateSchema() []*ResourceTemplateSchemaEntry {
	if x != nil {
		return x.ResourceTemplateSchema
	}
	return nil
}

// Extended by Higress
type MatchRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingress       []string               `protobuf:"bytes,1,rep,name=ingress,proto3" json:"ingress,omitempty"`
	Domain        []string               `protobuf:"bytes,2,rep,name=domain,proto3" json:"domain,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ConfigDisable *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=config_disable,json=configDisable,proto3" json:"config_disable,omitempty"`
	Service       []string               `protobuf:"bytes,5,rep,name=service,proto3" json:"service,omitempty"`
	// Route type for this match rule, defaults to HTTP
	RouteType     RouteType `protobuf:"varint,6,opt,name=route_type,json=routeType,proto3,enum=higress.extensions.v1alpha1.RouteType" json:"route_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRule) Reset() {
	*x = MatchRule{}
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRule) ProtoMessage() {}

func (x *MatchRule) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRule.ProtoReflect.Descriptor instead.
func (*MatchRule) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{1}
}

func (x *MatchRule) GetIngress() []string {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *MatchRule) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *MatchRule) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MatchRule) GetConfigDisable() *wrapperspb.BoolValue {
	if x != nil {
		return x.ConfigDisable
	}
	return nil
}

func (x *MatchRule) GetService() []string {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *MatchRule) GetRouteType() RouteType {
	if x != nil {
		return x.RouteType
	}
	return RouteType_HTTP
}

// Extended by Higress, template schema entry for config sharding
// Maps a ConfigMap data key to a placeholder name used in rendering
type ResourceTemplateSchemaEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key in ConfigMap's data field (e.g. "consumers", "matchRules")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The placeholder name (e.g. "consumers", "matchRules")
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTemplateSchemaEntry) Reset() {
	*x = ResourceTemplateSchemaEntry{}
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTemplateSchemaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTemplateSchemaEntry) ProtoMessage() {}

func (x *ResourceTemplateSchemaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTemplateSchemaEntry.ProtoReflect.Descriptor instead.
func (*ResourceTemplateSchemaEntry) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceTemplateSchemaEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResourceTemplateSchemaEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Configuration for a Wasm VM.
// more details can be found [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#extensions-wasm-v3-vmconfig).
type VmConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies environment variables to be injected to this VM.
	// Note that if a key does not exist, it will be ignored.
	Env           []*EnvVar `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmConfig) Reset() {
	*x = VmConfig{}
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmConfig) ProtoMessage() {}

func (x *VmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmConfig.ProtoReflect.Descriptor instead.
func (*VmConfig) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{3}
}

func (x *VmConfig) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

type EnvVar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required
	// Name of the environment variable. Must be a C_IDENTIFIER.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required
	// Source for the environment variable's value.
	ValueFrom EnvValueSource `protobuf:"varint,3,opt,name=value_from,json=valueFrom,proto3,enum=higress.extensions.v1alpha1.EnvValueSource" json:"value_from,omitempty"`
	// Value for the environment variable.
	// Note that if `value_from` is `HOST`, it will be ignored.
	// Defaults to "".
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_v1alpha1_wasmplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP(), []int{4}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValueFrom() EnvValueSource {
	if x != nil {
		return x.ValueFrom
	}
	return EnvValueSource_INLINE
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_extensions_v1alpha1_wasmplugin_proto protoreflect.FileDescriptor

const file_extensions_v1alpha1_wasmplugin_proto_rawDesc = "" +
	"\n" +
	"$extensions/v1alpha1/wasmplugin.proto\x12\x1bhigress.extensions.v1alpha1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc2\a\n" +
	"\n" +
	"WasmPlugin\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12S\n" +
	"\x11image_pull_policy\x18\x04 \x01(\x0e2'.higress.extensions.v1alpha1.PullPolicyR\x0fimagePullPolicy\x12*\n" +
	"\x11image_pull_secret\x18\x05 \x01(\tR\x0fimagePullSecret\x12)\n" +
	"\x10verification_key\x18\x06 \x01(\tR\x0fverificationKey\x12<\n" +
	"\rplugin_config\x18\a \x01(\v2\x17.google.protobuf.StructR\fpluginConfig\x12\x1f\n" +
	"\vplugin_name\x18\b \x01(\tR\n" +
	"pluginName\x12>\n" +
	"\x05phase\x18\t \x01(\x0e2(.higress.extensions.v1alpha1.PluginPhaseR\x05phase\x127\n" +
	"\bpriority\x18\n" +
	" \x01(\v2\x1b.google.protobuf.Int32ValueR\bpriority\x12N\n" +
	"\rfail_strategy\x18\r \x01(\x0e2).higress.extensions.v1alpha1.FailStrategyR\ffailStrategy\x12B\n" +
	"\tvm_config\x18\v \x01(\v2%.higress.extensions.v1alpha1.VmConfigR\bvmConfig\x12>\n" +
	"\x0edefault_config\x18e \x01(\v2\x17.google.protobuf.StructR\rdefaultConfig\x12G\n" +
	"\vmatch_rules\x18f \x03(\v2&.higress.extensions.v1alpha1.MatchRuleR\n" +
	"matchRules\x12P\n" +
	"\x16default_config_disable\x18g \x01(\v2\x1a.google.protobuf.BoolValueR\x14defaultConfigDisable\x12#\n" +
	"\rresource_refs\x18h \x03(\tR\fresourceRefs\x12r\n" +
	"\x18resource_template_schema\x18i \x03(\v28.higress.extensions.v1alpha1.ResourceTemplateSchemaEntryR\x16resourceTemplateSchema\"\x92\x02\n" +
	"\tMatchRule\x12\x18\n" +
	"\aingress\x18\x01 \x03(\tR\aingress\x12\x16\n" +
	"\x06domain\x18\x02 \x03(\tR\x06domain\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12A\n" +
	"\x0econfig_disable\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\rconfigDisable\x12\x18\n" +
	"\aservice\x18\x05 \x03(\tR\aservice\x12E\n" +
	"\n" +
	"route_type\x18\x06 \x01(\x0e2&.higress.extensions.v1alpha1.RouteTypeR\trouteType\"E\n" +
	"\x1bResourceTemplateSchemaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\bVmConfig\x125\n" +
	"\x03env\x18\x01 \x03(\v2#.higress.extensions.v1alpha1.EnvVarR\x03env\"~\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\n" +
	"value_from\x18\x03 \x01(\x0e2+.higress.extensions.v1alpha1.EnvValueSourceR\tvalueFrom\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*\x1f\n" +
	"\tRouteType\x12\b\n" +
	"\x04HTTP\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01*E\n" +
	"\vPluginPhase\x12\x15\n" +
	"\x11UNSPECIFIED_PHASE\x10\x00\x12\t\n" +
	"\x05AUTHN\x10\x01\x12\t\n" +
	"\x05AUTHZ\x10\x02\x12\t\n" +
	"\x05STATS\x10\x03*B\n" +
	"\n" +
	"PullPolicy\x12\x16\n" +
	"\x12UNSPECIFIED_POLICY\x10\x00\x12\x10\n" +
	"\fIfNotPresent\x10\x01\x12\n" +
	"\n" +
	"\x06Always\x10\x02*&\n" +
	"\x0eEnvValueSource\x12\n" +
	"\n" +
	"\x06INLINE\x10\x00\x12\b\n" +
	"\x04HOST\x10\x01*-\n" +
	"\fFailStrategy\x12\x0e\n" +
	"\n" +
	"FAIL_CLOSE\x10\x00\x12\r\n" +
	"\tFAIL_OPEN\x10\x01B7Z5github.com/alibaba/higress/v2/api/extensions/v1alpha1b\x06proto3"

var (
	file_extensions_v1alpha1_wasmplugin_proto_rawDescOnce sync.Once
	file_extensions_v1alpha1_wasmplugin_proto_rawDescData []byte
)

func file_extensions_v1alpha1_wasmplugin_proto_rawDescGZIP() []byte {
	file_extensions_v1alpha1_wasmplugin_proto_rawDescOnce.Do(func() {
		file_extensions_v1alpha1_wasmplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_v1alpha1_wasmplugin_proto_rawDesc), len(file_extensions_v1alpha1_wasmplugin_proto_rawDesc)))
	})
	return file_extensions_v1alpha1_wasmplugin_proto_rawDescData
}

var file_extensions_v1alpha1_wasmplugin_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_extensions_v1alpha1_wasmplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_extensions_v1alpha1_wasmplugin_proto_goTypes = []any{
	(RouteType)(0),                      // 0: higress.extensions.v1alpha1.RouteType
	(PluginPhase)(0),                    // 1: higress.extensions.v1alpha1.PluginPhase
	(PullPolicy)(0),                     // 2: higress.extensions.v1alpha1.PullPolicy
	(EnvValueSource)(0),                 // 3: higress.extensions.v1alpha1.EnvValueSource
	(FailStrategy)(0),                   // 4: higress.extensions.v1alpha1.FailStrategy
	(*WasmPlugin)(nil),                  // 5: higress.extensions.v1alpha1.WasmPlugin
	(*MatchRule)(nil),                   // 6: higress.extensions.v1alpha1.MatchRule
	(*ResourceTemplateSchemaEntry)(nil), // 7: higress.extensions.v1alpha1.ResourceTemplateSchemaEntry
	(*VmConfig)(nil),                    // 8: higress.extensions.v1alpha1.VmConfig
	(*EnvVar)(nil),                      // 9: higress.extensions.v1alpha1.EnvVar
	(*structpb.Struct)(nil),             // 10: google.protobuf.Struct
	(*wrapperspb.Int32Value)(nil),       // 11: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),        // 12: google.protobuf.BoolValue
}
var file_extensions_v1alpha1_wasmplugin_proto_depIdxs = []int32{
	2,  // 0: higress.extensions.v1alpha1.WasmPlugin.image_pull_policy:type_name -> higress.extensions.v1alpha1.PullPolicy
	10, // 1: higress.extensions.v1alpha1.WasmPlugin.plugin_config:type_name -> google.protobuf.Struct
	1,  // 2: higress.extensions.v1alpha1.WasmPlugin.phase:type_name -> higress.extensions.v1alpha1.PluginPhase
	11, // 3: higress.extensions.v1alpha1.WasmPlugin.priority:type_name -> google.protobuf.Int32Value
	4,  // 4: higress.extensions.v1alpha1.WasmPlugin.fail_strategy:type_name -> higress.extensions.v1alpha1.FailStrategy
	8,  // 5: higress.extensions.v1alpha1.WasmPlugin.vm_config:type_name -> higress.extensions.v1alpha1.VmConfig
	10, // 6: higress.extensions.v1alpha1.WasmPlugin.default_config:type_name -> google.protobuf.Struct
	6,  // 7: higress.extensions.v1alpha1.WasmPlugin.match_rules:type_name -> higress.extensions.v1alpha1.MatchRule
	12, // 8: higress.extensions.v1alpha1.WasmPlugin.default_config_disable:type_name -> google.protobuf.BoolValue
	7,  // 9: higress.extensions.v1alpha1.WasmPlugin.resource_template_schema:type_name -> higress.extensions.v1alpha1.ResourceTemplateSchemaEntry
	10, // 10: higress.extensions.v1alpha1.MatchRule.config:type_name -> google.protobuf.Struct
	12, // 11: higress.extensions.v1alpha1.MatchRule.config_disable:type_name -> google.protobuf.BoolValue
	0,  // 12: higress.extensions.v1alpha1.MatchRule.route_type:type_name -> higress.extensions.v1alpha1.RouteType
	9,  // 13: higress.extensions.v1alpha1.VmConfig.env:type_name -> higress.extensions.v1alpha1.EnvVar
	3,  // 14: higress.extensions.v1alpha1.EnvVar.value_from:type_name -> higress.extensions.v1alpha1.EnvValueSource
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_extensions_v1alpha1_wasmplugin_proto_init() }
func file_extensions_v1alpha1_wasmplugin_proto_init() {
	if File_extensions_v1alpha1_wasmplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_v1alpha1_wasmplugin_proto_rawDesc), len(file_extensions_v1alpha1_wasmplugin_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_v1alpha1_wasmplugin_proto_goTypes,
		DependencyIndexes: file_extensions_v1alpha1_wasmplugin_proto_depIdxs,
		EnumInfos:         file_extensions_v1alpha1_wasmplugin_proto_enumTypes,
		MessageInfos:      file_extensions_v1alpha1_wasmplugin_proto_msgTypes,
	}.Build()
	File_extensions_v1alpha1_wasmplugin_proto = out.File
	file_extensions_v1alpha1_wasmplugin_proto_goTypes = nil
	file_extensions_v1alpha1_wasmplugin_proto_depIdxs = nil
}
